#!/usr/bin/env bash
tab=$'\t'
fzf_args=("--delimiter=${tab}" '--with-nth=1..2' '--ansi')

column_args=(
  '--table'
  '--table-noheadings'
  '--separator'
  "$tab"
  '--output-separator'
  "$tab"
  '--table-columns'
  'Name,Description,ID,Remote'
)
flatpak_args=('--columns=name,description,application,remotes')

# If no query provided from cli, ask for input
if [[ -z $1 ]]; then
  read -rp 'Search: ' -a query
else
  query=("$@")
fi

mapfile -t id < <(flatpak search "${flatpak_args[@]}" -- "${query[@]}" |
  column "${column_args[@]}" | fzf "${fzf_args[@]}" |
  awk -v 'OFS=\n' '{print $(NF-1), $NF}')

if [[ -z ${id[*]} ]]; then
  echo "No program selected."
  exit 0
fi

exec flatpak install "${id[1]}" "${id[0]}"
